import type { StaticImageData } from "next/image";

// Web-sized copies generated by `npm run photos` (see scripts/optimize-photos.mjs).
import DSC01136 from "@/photos/DSC01136.jpg";
import DSC01411 from "@/photos/DSC01411.jpg";
import DSC01420 from "@/photos/DSC01420.jpg";
import DSC01441 from "@/photos/DSC01441.jpg";
import DSC01533 from "@/photos/DSC01533.jpg";
import DSC01682 from "@/photos/DSC01682.jpg";
import DSC01974Enhanced from "@/photos/DSC01974-Enhanced-NR.jpg";
import DSC02008 from "@/photos/DSC02008.jpg";
import DSC02193 from "@/photos/DSC02193.jpg";
import DSC02231Enhanced from "@/photos/DSC02231-Enhanced-NR.jpg";
import DSC02252 from "@/photos/DSC02252.jpg";
import DSC02412 from "@/photos/DSC02412.jpg";
import DSC02418 from "@/photos/DSC02418.jpg";
import DSC02453 from "@/photos/DSC02453.jpg";
import DSC02784 from "@/photos/DSC02784.jpg";
import DSC06783 from "@/photos/DSC06783.jpg";
import DSC06822 from "@/photos/DSC06822.jpg";
import DSC06873 from "@/photos/DSC06873.jpg";
import DSC06915 from "@/photos/DSC06915.jpg";
import DSC07009 from "@/photos/DSC07009.jpg";
import DSC07041 from "@/photos/DSC07041.jpg";
import DSC07112 from "@/photos/DSC07112.jpg";
import DSC07113 from "@/photos/DSC07113.jpg";
import DSC07132 from "@/photos/DSC07132.jpg";
import DSC07168 from "@/photos/DSC07168.jpg";
import DSC07185 from "@/photos/DSC07185.jpg";
import DSC07207 from "@/photos/DSC07207.jpg";
import DSC07313Panorama from "@/photos/DSC07313-Panorama.jpg";
import L1003012 from "@/photos/L1003012.jpg";
import L1003502 from "@/photos/L1003502.jpg";
import L1003566 from "@/photos/L1003566.jpg";
import L1003588 from "@/photos/L1003588.jpg";
import L1003637 from "@/photos/L1003637.jpg";
import L1003639 from "@/photos/L1003639.jpg";
import L1003684 from "@/photos/L1003684.jpg";
import L1004068 from "@/photos/L1004068.jpg";
import L1004071 from "@/photos/L1004071.jpg";
import L1004099 from "@/photos/L1004099.jpg";
import L1004227 from "@/photos/L1004227.jpg";
import L1004258 from "@/photos/L1004258.jpg";
import L1004895 from "@/photos/L1004895.jpg";
import L1004966 from "@/photos/L1004966.jpg";

export type Photo = {
  id: string;
  src: StaticImageData;
  alt: string;
  title: string;
  year: string;
};

/** Hanging height on the wall, as a share of the viewport height. */
export type WorkSize = "s" | "m" | "l";

/**
 * The exhibition is one long wall, read left to right:
 * - work: a hung photograph; `tight` hangs the next one close, as a pair
 * - text: a wall text introducing a series
 */
export type WallItem =
  | { kind: "work"; photo: Photo; size: WorkSize; tight?: boolean }
  | { kind: "text"; title: string; meta: string };

const photo = (id: string, src: StaticImageData, title: string, year: string, alt: string): Photo => ({
  id,
  src,
  title,
  year,
  alt
});

const work = (p: Photo, size: WorkSize, tight = false): WallItem => ({ kind: "work", photo: p, size, tight });
const text = (title: string, meta: string): WallItem => ({ kind: "text", title, meta });

export const hero = photo("dsc01136", DSC01136, "Village — Lofoten", "2024",
  "Fishing village under snowy mountains at dusk, Lofoten");

/** The photographer, introducing the exhibition next to its title. */
export const portrait = photo("dsc06822", DSC06822, "Cédric Benet — Fjallabak", "2025",
  "Cédric Benet hiking with a red backpack above a canyon in the Icelandic highlands");

/** Photo from which the gallery lights dim to night (see ExhibitionWall). */
export const LIGHTS_OUT_ID = "l1003566";

export const wall: WallItem[] = [
  text("Norvège", "Lofoten — 2024"),
  work(photo("dsc01974", DSC01974Enhanced, "Mer de Norvège", "2024",
    "Midnight sun over the Norwegian sea and mountains"), "m"),
  work(photo("dsc02193", DSC02193, "Pygargue", "2024", "White-tailed eagle in flight"), "s", true),
  work(photo("dsc02231", DSC02231Enhanced, "Le guetteur", "2024",
    "Eagle perched on a rock while another flies above snowy mountains"), "m"),
  work(photo("dsc02008", DSC02008, "Deux pygargues", "2024",
    "Two white-tailed eagles flying over a fjord and snowy peaks"), "l"),
  work(photo("dsc02252", DSC02252, "La prise", "2024",
    "Eagle catching a fish in front of snowy peaks, black and white"), "m"),
  work(photo("dsc01441", DSC01441, "Fjord", "2024",
    "Streaked clouds over a fjord with small islands and snowy mountains"), "l", true),
  work(photo("dsc01411", DSC01411, "Sommet", "2024", "Snow-covered peak under heavy clouds"), "s"),
  work(photo("dsc01420", DSC01420, "Versant", "2024", "Snowy mountain slopes under a bright cloudy sky"), "m"),
  work(photo("dsc01533", DSC01533, "Arêtes", "2024", "Wind-sculpted snowy ridge against a blue sky"), "m"),
  work(photo("dsc02412", DSC02412, "Séchoirs", "2024", "Cod drying racks, black and white"), "m", true),
  work(photo("dsc02418", DSC02418, "Stockfisch", "2024", "Stockfish rack on a rocky shore, black and white"), "m", true),
  work(photo("dsc02453", DSC02453, "Rorbu", "2024",
    "Red fishermen's cabins reflected upside down in still water"), "m"),
  work(photo("dsc01682", DSC01682, "Silhouettes", "2024",
    "Layered mountain silhouettes and a church in amber haze"), "l"),
  work(photo("dsc02784", DSC02784, "Aurore", "2024", "Green aurora borealis over silhouetted trees"), "l"),

  text("Hautes terres", "Islande, Fjallabak — 2025"),
  work(photo("dsc07041", DSC07041, "Fjallabak", "2025",
    "Panorama of green volcanic highlands and a small lake, Iceland"), "m"),
  work(photo("dsc06873", DSC06873, "Mælifell", "2025",
    "Moss-covered cone of Mælifell rising from black sand, Iceland"), "m", true),
  work(photo("dsc06915", DSC06915, "Avant l'orage", "2025", "Mælifell lit by sun under dark storm clouds"), "s"),
  work(photo("dsc07009", DSC07009, "Vallée", "2025",
    "River winding through a green valley toward a pointed peak"), "l", true),
  work(photo("dsc07132", DSC07132, "Névé", "2025", "Snowfield below a snow-capped summit in a barren valley"), "l"),
  work(photo("dsc07185", DSC07185, "Landmannalaugar", "2025",
    "Hiker in a red jacket overlooking rhyolite mountains, Landmannalaugar"), "l"),
  work(photo("dsc07207", DSC07207, "Rhyolites", "2025", "Multicoloured rhyolite mountains under a blue sky"), "s"),
  work(photo("dsc07313-panorama", DSC07313Panorama, "Landmannalaugar, panorama", "2025",
    "Panorama of ochre and green rhyolite mountains under a grey sky, Landmannalaugar"), "l"),
  work(photo("dsc07112", DSC07112, "Hautes terres", "2025", "Volcanic highlands under a stormy sky, Iceland"), "m"),
  work(photo("dsc07168", DSC07168, "Fumerolles", "2025", "Steaming geothermal vents in dark hills"), "m"),
  work(photo("dsc06783", DSC06783, "Racines", "2025",
    "Tangled roots on black ground below a stormy sky, black and white"), "l"),
  work(photo("dsc07113", DSC07113, "Le sentier", "2025",
    "Trail through brown hills with patches of snow and a lone hiker"), "s"),

  text("Islande", "Côtes, villages et volcans — 2022 · 2023"),
  work(photo("l1003502", L1003502, "Le phare", "2022",
    "Orange lighthouse on a grassy headland facing mountains"), "m"),
  work(photo("l1003012", L1003012, "Seljalandsfoss", "2022", "Waterfall seen from behind the curtain of water"), "l"),
  work(photo("l1004068", L1004068, "Toit de tourbe", "2022", "White house with a grass turf roof"), "m", true),
  work(photo("l1004071", L1004071, "Maisons de tourbe", "2022", "Stone path leading to turf houses"), "m"),
  work(photo("l1004099", L1004099, "Église", "2022",
    "White wooden church behind a picket gate, black and white"), "l"),
  work(photo("l1004258", L1004258, "Éruption", "2022",
    "Volcanic eruption with lava fountains and smoke over a lava field"), "l"),
  work(photo("l1004227", L1004227, "Coulée", "2022", "Glowing vent on the horizon beyond a dark lava field"), "s"),
  work(photo("l1003566", L1003566, "Crépuscule", "2022", "Mountain silhouettes against a purple twilight sky"), "m"),
  work(photo("l1003588", L1003588, "Veille", "2022", "Lit cabin between trees at night"), "m", true),
  work(photo("l1003684", L1003684, "Façade", "2022", "Lit windows of a house under a tree at night"), "m"),
  work(photo("l1003637", L1003637, "Reflets", "2022", "Houses reflected in still water at blue hour"), "m"),
  work(photo("l1003639", L1003639, "Fjord la nuit", "2022", "Village lights along a fjord at night"), "l"),
  work(photo("l1004966", L1004966, "Hiver", "2023",
    "Houses and a tree strung with lights on a winter night"), "m", true),
  work(photo("l1004895", L1004895, "Fenêtre", "2023", "Warmly lit window on a dark corrugated facade"), "s")
];

/** Every hung photo in wall order: drives the lightbox and the cartel numbers. */
export const photos: Photo[] = wall.flatMap(item => (item.kind === "work" ? [item.photo] : []));

export function aspect(p: Photo): number {
  return p.src.width / p.src.height;
}
