import type { StaticImageData } from "next/image";

// Web-sized copies generated by `npm run photos` (see scripts/optimize-photos.mjs).
import DSC01136 from "@/photos/DSC01136.jpg";
import DSC01411 from "@/photos/DSC01411.jpg";
import DSC01441 from "@/photos/DSC01441.jpg";
import DSC01533 from "@/photos/DSC01533.jpg";
import DSC01974Enhanced from "@/photos/DSC01974-Enhanced-NR.jpg";
import DSC02008 from "@/photos/DSC02008.jpg";
import DSC02193 from "@/photos/DSC02193.jpg";
import DSC02231Enhanced from "@/photos/DSC02231-Enhanced-NR.jpg";
import DSC02252 from "@/photos/DSC02252.jpg";
import DSC02412 from "@/photos/DSC02412.jpg";
import DSC02418 from "@/photos/DSC02418.jpg";
import DSC02784 from "@/photos/DSC02784.jpg";
import DSC06783 from "@/photos/DSC06783.jpg";
import DSC06873 from "@/photos/DSC06873.jpg";
import DSC06915 from "@/photos/DSC06915.jpg";
import DSC07009 from "@/photos/DSC07009.jpg";
import DSC07041 from "@/photos/DSC07041.jpg";
import DSC07112 from "@/photos/DSC07112.jpg";
import DSC07113 from "@/photos/DSC07113.jpg";
import DSC07132 from "@/photos/DSC07132.jpg";
import DSC07168 from "@/photos/DSC07168.jpg";
import DSC07185 from "@/photos/DSC07185.jpg";
import DSC07207 from "@/photos/DSC07207.jpg";
import DSC07313Panorama from "@/photos/DSC07313-Panorama.jpg";
import L1003012 from "@/photos/L1003012.jpg";
import L1003502 from "@/photos/L1003502.jpg";
import L1003566 from "@/photos/L1003566.jpg";
import L1003588 from "@/photos/L1003588.jpg";
import L1003637 from "@/photos/L1003637.jpg";
import L1003639 from "@/photos/L1003639.jpg";
import L1003684 from "@/photos/L1003684.jpg";
import L1004068 from "@/photos/L1004068.jpg";
import L1004071 from "@/photos/L1004071.jpg";
import L1004099 from "@/photos/L1004099.jpg";
import L1004227 from "@/photos/L1004227.jpg";
import L1004258 from "@/photos/L1004258.jpg";
import L1004895 from "@/photos/L1004895.jpg";
import L1004966 from "@/photos/L1004966.jpg";

/**
 * Controls each photo's width and horizontal placement in the editorial flow.
 * "panorama" pins full-height and pans sideways (PanoramaSection).
 */
export type PhotoLayout =
  | "full"
  | "wide-left"
  | "wide-right"
  | "portrait-center"
  | "portrait-right"
  | "panorama";

export type PhotoItem = {
  id: string;
  src: StaticImageData;
  alt: string;
  title: string;
  year: string;
  layout: PhotoLayout;
};

export const photos: PhotoItem[] = [
  // ── Norvège ──
  {
    id: "dsc01136",
    src: DSC01136,
    alt: "Fishing village under snowy mountains at dusk, Lofoten",
    title: "Village — Lofoten",
    year: "2026",
    layout: "full"
  },
  {
    id: "dsc01974",
    src: DSC01974Enhanced,
    alt: "Midnight sun over the Norwegian sea and mountains",
    title: "Mer de Norvège",
    year: "2026",
    layout: "wide-right"
  },
  {
    id: "dsc01533",
    src: DSC01533,
    alt: "Wind-sculpted snowy ridge against a blue sky",
    title: "Arêtes",
    year: "2024",
    layout: "wide-left"
  },
  {
    id: "dsc02193",
    src: DSC02193,
    alt: "White-tailed eagle in flight",
    title: "Pygargue",
    year: "2026",
    layout: "portrait-center"
  },
  {
    id: "dsc02008",
    src: DSC02008,
    alt: "Two white-tailed eagles flying over a fjord and snowy peaks",
    title: "Deux pygargues",
    year: "2024",
    layout: "full"
  },
  {
    id: "dsc02231",
    src: DSC02231Enhanced,
    alt: "Eagle perched on a rock while another flies above snowy mountains",
    title: "Le guetteur",
    year: "2024",
    layout: "portrait-right"
  },
  {
    id: "dsc02252",
    src: DSC02252,
    alt: "Eagle catching a fish in front of snowy peaks, black and white",
    title: "La prise",
    year: "2026",
    layout: "wide-left"
  },
  {
    id: "dsc01441",
    src: DSC01441,
    alt: "Streaked clouds over a fjord with small islands and snowy mountains",
    title: "Fjord",
    year: "2024",
    layout: "portrait-center"
  },
  {
    id: "dsc02412",
    src: DSC02412,
    alt: "Cod drying racks, black and white",
    title: "Séchoirs",
    year: "2026",
    layout: "full"
  },
  {
    id: "dsc02418",
    src: DSC02418,
    alt: "Stockfish rack on a rocky shore, black and white",
    title: "Stockfisch",
    year: "2026",
    layout: "portrait-right"
  },
  {
    id: "dsc01411",
    src: DSC01411,
    alt: "Snow-covered peak under heavy clouds",
    title: "Sommet",
    year: "2024",
    layout: "portrait-center"
  },
  {
    id: "dsc02784",
    src: DSC02784,
    alt: "Green aurora borealis over silhouetted trees",
    title: "Aurore",
    year: "2026",
    layout: "portrait-right"
  },

  // ── Islande — hautes terres ──
  {
    id: "dsc07041",
    src: DSC07041,
    alt: "Panorama of green volcanic highlands and a small lake, Iceland",
    title: "Fjallabak",
    year: "2025",
    layout: "full"
  },
  {
    id: "dsc06873",
    src: DSC06873,
    alt: "Moss-covered cone of Mælifell rising from black sand, Iceland",
    title: "Mælifell",
    year: "2025",
    layout: "wide-right"
  },
  {
    id: "dsc07009",
    src: DSC07009,
    alt: "River winding through a green valley toward a pointed peak",
    title: "Vallée",
    year: "2025",
    layout: "portrait-center"
  },
  {
    id: "dsc07112",
    src: DSC07112,
    alt: "Volcanic highlands under a stormy sky, Iceland",
    title: "Hautes terres — Islande",
    year: "2025",
    layout: "wide-left"
  },
  {
    id: "dsc07132",
    src: DSC07132,
    alt: "Snowfield below a snow-capped summit in a barren valley",
    title: "Névé",
    year: "2025",
    layout: "portrait-right"
  },
  {
    id: "dsc07185",
    src: DSC07185,
    alt: "Hiker in a red jacket overlooking rhyolite mountains, Landmannalaugar",
    title: "Landmannalaugar",
    year: "2025",
    layout: "full"
  },
  {
    id: "dsc07207",
    src: DSC07207,
    alt: "Multicoloured rhyolite mountains under a blue sky",
    title: "Rhyolites",
    year: "2025",
    layout: "wide-left"
  },
  {
    id: "dsc07313-panorama",
    src: DSC07313Panorama,
    alt: "Panorama of ochre and green rhyolite mountains under a grey sky, Landmannalaugar",
    title: "Panorama — Landmannalaugar",
    year: "2025",
    layout: "panorama"
  },
  {
    id: "dsc06783",
    src: DSC06783,
    alt: "Tangled roots on black ground below a stormy sky, black and white",
    title: "Racines",
    year: "2025",
    layout: "portrait-center"
  },
  {
    id: "dsc07168",
    src: DSC07168,
    alt: "Steaming geothermal vents in dark hills",
    title: "Fumerolles",
    year: "2025",
    layout: "wide-right"
  },
  {
    id: "dsc07113",
    src: DSC07113,
    alt: "Trail through brown hills with patches of snow and a lone hiker",
    title: "Le sentier",
    year: "2025",
    layout: "wide-left"
  },
  {
    id: "dsc06915",
    src: DSC06915,
    alt: "Mælifell lit by sun under dark storm clouds",
    title: "Avant l'orage",
    year: "2025",
    layout: "full"
  },

  // ── Islande ──
  {
    id: "l1003012",
    src: L1003012,
    alt: "Waterfall seen from behind the curtain of water",
    title: "Seljalandsfoss",
    year: "2022",
    layout: "portrait-right"
  },
  {
    id: "l1003502",
    src: L1003502,
    alt: "Orange lighthouse on a grassy headland facing mountains",
    title: "Le phare",
    year: "2022",
    layout: "wide-left"
  },
  {
    id: "l1003566",
    src: L1003566,
    alt: "Mountain silhouettes against a purple twilight sky",
    title: "Crépuscule",
    year: "2022",
    layout: "full"
  },
  {
    id: "l1003588",
    src: L1003588,
    alt: "Lit cabin between trees at night",
    title: "Veille",
    year: "2022",
    layout: "portrait-center"
  },
  {
    id: "l1003637",
    src: L1003637,
    alt: "Houses reflected in still water at blue hour",
    title: "Reflets",
    year: "2022",
    layout: "wide-right"
  },
  {
    id: "l1003639",
    src: L1003639,
    alt: "Village lights along a fjord at night",
    title: "Fjord la nuit",
    year: "2022",
    layout: "full"
  },
  {
    id: "l1003684",
    src: L1003684,
    alt: "Lit windows of a house under a tree at night",
    title: "Façade",
    year: "2022",
    layout: "portrait-right"
  },
  {
    id: "l1004068",
    src: L1004068,
    alt: "White house with a grass turf roof",
    title: "Toit de tourbe",
    year: "2022",
    layout: "wide-left"
  },
  {
    id: "l1004071",
    src: L1004071,
    alt: "Stone path leading to turf houses",
    title: "Maisons de tourbe",
    year: "2022",
    layout: "portrait-center"
  },
  {
    id: "l1004099",
    src: L1004099,
    alt: "White wooden church behind a picket gate, black and white",
    title: "Église",
    year: "2022",
    layout: "portrait-right"
  },
  {
    id: "l1004258",
    src: L1004258,
    alt: "Volcanic eruption with lava fountains and smoke over a lava field",
    title: "Éruption",
    year: "2022",
    layout: "full"
  },
  {
    id: "l1004227",
    src: L1004227,
    alt: "Glowing vent on the horizon beyond a dark lava field",
    title: "Coulée",
    year: "2022",
    layout: "portrait-center"
  },
  {
    id: "l1004966",
    src: L1004966,
    alt: "Houses and a tree strung with lights on a winter night",
    title: "Hiver",
    year: "2023",
    layout: "wide-right"
  },
  {
    id: "l1004895",
    src: L1004895,
    alt: "Warmly lit window on a dark corrugated facade",
    title: "Fenêtre",
    year: "2023",
    layout: "portrait-center"
  }
];
